apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: postgres
  namespace: db
spec:
  instances: 1
  imageName: ghcr.io/cloudnative-pg/postgresql:16

  serviceAccountTemplate:
    metadata:
      annotations:
        eks.amazonaws.com/role-arn: arn:aws:iam::929861724743:role/pip-dev-cnpg-irsa-role

  storage:
    size: 5Gi
    storageClass: gp2

  postgresql:
    parameters:
      archive_timeout: "60"    # max 60 seconds data loss on failure

  bootstrap:
    initdb:
      database: taskflow
      owner: taskflow
      secret:
        name: taskflow-db-credentials

  backup:
    barmanObjectStore:
      destinationPath: s3://pip-taskflow-wal-dev/postgres
      s3Credentials:
        inheritFromIAMRole: true
      wal:
        compression: gzip
      data:
        compression: gzip
    retentionPolicy: "7d"