apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-config
  namespace: db
data:
  postgresql.conf: |
    wal_level = replica
    max_wal_senders = 3
    wal_keep_size = 1GB
    listen_addresses = '*'
  pg_hba.conf: |
    # Allow normal app connections
    host    all             all             0.0.0.0/0        scram-sha-256
    # Allow replication user from Hyderabad VPC CIDR
    host    replication     replicator      10.1.0.0/16      scram-sha-256