apiVersion: autoscaling.k8s.io/v1
kind: VerticalPodAutoscaler
metadata:
  name: postgres-vpa
  namespace: db
spec:
  targetRef:
    apiVersion: "apps/v1"
    kind: StatefulSet
    name: postgres

  updatePolicy:
    updateMode: "Initial"  # We will trigger updates manually after testing

  resourcePolicy:
    containerPolicies:
      - containerName: postgres
        minAllowed:
          cpu: 200m
          memory: 512Mi
        maxAllowed:
          cpu: "1"
          memory: 1GiA